"""Build the photo gallery (gallery.html) from photo_gallery/.

    photo_gallery/
        albums.json          titles, dates, descriptions, captions, album order;
                             the album marked "banner": true is the rotating banner at the top
        <album folder>/      original photos (any size) -- not published
        web/<album folder>/  web-sized copies made by this script -- published

Add photos to an album folder (or make a new folder), then run:
    python tools/build_gallery.py
New folders that are not yet in albums.json are added to it automatically
(with the folder name as title), so you only need to fill in the details.
"""
import json
import re
from pathlib import Path

from PIL import Image, ImageOps

ROOT = Path(__file__).resolve().parent.parent
GAL = ROOT / "photo_gallery"
WEB = GAL / "web"
CONFIG = GAL / "albums.json"
OUT = ROOT / "assets" / "js" / "gallery-data.js"
EXTS = {".jpg", ".jpeg", ".png", ".webp", ".heic"}
LONG_SIDE = 1800


def photos_in(folder):
    try:
        return sorted(p for p in folder.iterdir() if p.is_file() and p.suffix.lower() in EXTS)
    except OSError:
        return []


def web_name(src):
    """Web-safe file name: lower case, no spaces."""
    return re.sub(r"[^a-z0-9._-]+", "-", src.stem.lower()).strip("-") + ".jpg"


def web_copy(src, album):
    dst = WEB / album.lower() / web_name(src)
    if not dst.exists() or dst.stat().st_mtime < src.stat().st_mtime:
        dst.parent.mkdir(parents=True, exist_ok=True)
        im = ImageOps.exif_transpose(Image.open(src)).convert("RGB")
        im.thumbnail((LONG_SIDE, LONG_SIDE), Image.LANCZOS)
        im.save(dst, "JPEG", quality=82, optimize=True, progressive=True)
        print(f"  resized {src.name} -> web/{album.lower()}/{dst.name} ({dst.stat().st_size // 1024} KB)")
    return dst.name


def main():
    cfg = json.loads(CONFIG.read_text(encoding="utf8"))
    albums = cfg.setdefault("albums", [])

    def folders_of(a):  # an album can draw on one folder ("folder") or several ("folders")
        return a.get("folders") or [a["folder"]]

    known = {f for a in albums for f in folders_of(a)}

    # new folders -> new albums (at the end; move them in albums.json to reorder)
    for folder in sorted(p for p in GAL.iterdir() if p.is_dir() and p.name != "web"):
        if folder.name not in known and photos_in(folder):
            albums.append({"folder": folder.name, "title": folder.name.replace("_", " ").replace("-", " ").title(),
                           "date": "", "description": "", "captions": {}})
            print(f"New album '{folder.name}' added to albums.json -- fill in its title, date and description.")
    CONFIG.write_text(json.dumps(cfg, indent=4, ensure_ascii=False) + "\n", encoding="utf8")

    data = []
    for a in albums:
        files = [(f, p) for f in folders_of(a) for p in photos_in(GAL / f)]
        if not files:
            print(f"Skipping '{a['title']}': no photos yet.")
            continue
        order = a.get("order", [])
        files.sort(key=lambda fp: (order.index(fp[1].name) if fp[1].name in order else len(order), fp[0], fp[1].name))
        print(f"{a['title']}: {len(files)} photos")
        photos = [{"file": f"photo_gallery/web/{f.lower()}/{web_copy(p, f)}", "caption": a.get("captions", {}).get(p.name, "")}
                  for f, p in files]
        data.append({"title": a["title"], "date": a.get("date", ""), "description": a.get("description", ""),
                     "banner": bool(a.get("banner")), "folder": "", "photos": photos})

    # remove web copies whose original is gone (and folders left empty)
    # web folder names are lower case (web servers are case-sensitive, Windows is not)
    originals = {p.name.lower(): p for p in GAL.iterdir() if p.is_dir() and p.name != "web"}
    for folder in list(WEB.iterdir()) if WEB.exists() else []:
        src = originals.get(folder.name.lower())
        keep = {web_name(p) for p in photos_in(src)} if src else set()
        for f in folder.iterdir():
            if f.name not in keep:
                f.unlink()
                print(f"  removed stale web/{folder.name}/{f.name}")
        if not any(folder.iterdir()):
            folder.rmdir()

    OUT.write_text("// Generated by tools/build_gallery.py from photo_gallery/albums.json -- edit that, not this file.\n"
                   "window.GALLERY_ALBUMS = " + json.dumps(data, indent=4, ensure_ascii=False) + ";\n", encoding="utf8")
    print(f"Wrote {OUT.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
